# Generated by Django 4.2.17 on 2025-04-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_add_address_to_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
        ),
    ]
