# Generated by Django 4.2.17 on 2025-05-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="profit",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
