# Generated by Django 4.2.17 on 2025-05-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_order_amount_alter_order_created_at_and_more"),
    ]

    operations = [
       
        migrations.AlterField(
            model_name="mailingmessage",
            name="text",
            field=models.TextField(verbose_name="Текст сообщения"),
        ),
    ]
