# Generated by Django 4.2.24 on 2025-09-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailingmessage_description_alter_mailingmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (анонс)'),
        ),
    ]
