# Generated by Django 4.2.24 on 2025-11-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mailingmessage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerdiscount',
            options={'verbose_name': 'Персональная скидка покупателя', 'verbose_name_plural': 'Персональные скидки покупателей'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'verbose_name': 'Программа лояльности', 'verbose_name_plural': 'Программы лояльности'},
        ),
        migrations.AlterModelOptions(
            name='organizerdiscount',
            options={'verbose_name': 'Скидка между организаторами', 'verbose_name_plural': 'Скидки между организаторами'},
        ),
    ]
